// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCax6-0e04V3ErqwIfe7DhhfNp4psrqods',
    appId: '1:499864869995:web:9b49c209e12f85445da52e',
    messagingSenderId: '499864869995',
    projectId: 'testeqrpayment',
    authDomain: 'testeqrpayment.firebaseapp.com',
    storageBucket: 'testeqrpayment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWaNmdYBeZsO6goycxMgmOr-bFjaz2Xhc',
    appId: '1:499864869995:android:03d75e1dadd968e85da52e',
    messagingSenderId: '499864869995',
    projectId: 'testeqrpayment',
    storageBucket: 'testeqrpayment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhosDPICTgEhnkgi4LPV_gk_qJ9Qf8-M',
    appId: '1:499864869995:ios:086124fe296ad62a5da52e',
    messagingSenderId: '499864869995',
    projectId: 'testeqrpayment',
    storageBucket: 'testeqrpayment.appspot.com',
    iosClientId: '499864869995-0cr3ddhqotpd8pgst15to6h9d0pm8b7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcodeTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhosDPICTgEhnkgi4LPV_gk_qJ9Qf8-M',
    appId: '1:499864869995:ios:086124fe296ad62a5da52e',
    messagingSenderId: '499864869995',
    projectId: 'testeqrpayment',
    storageBucket: 'testeqrpayment.appspot.com',
    iosClientId: '499864869995-0cr3ddhqotpd8pgst15to6h9d0pm8b7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcodeTeste',
  );
}
